### ISSUE TITLE
bug(matomo): Matomo has not yet been initialized

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#984]
**Description du problème**

Message d'erreur dans les logs de travis: https://travis-ci.com/github/SocialGouv/domifa/builds/203505345

**Comportement attendu**

Il faut pouvoir activer/désactiver matomo par environnement (par défaut, actif seulement en prod).

Si il est inactif, pas de message d'erreur dans les logs.

**Recette PO**

Rien à tester, le test s'effectuera directement sur la PR, en vérifiant que le message d'erreur a disparu.

**Comment by Toub** [comment]
Trace: 
```bash
      Matomo has not yet been initialized! (Did you forget to inject it?)
      at new MatomoTracker (node_modules/out-tsc/lib/src/service/matomo-tracker.service.ts:23:21)
      at _createClass (../packages/core/src/view/ng_module.ts:178:14)
      at _createProviderInstance (../packages/core/src/view/ng_module.ts:150:20)
      at resolveNgModuleDep (../packages/core/src/view/ng_module.ts:109:13)
      at NgModuleRef_.get (../packages/core/src/view/refs.ts:420:12)
      at resolveDep (../packages/core/src/view/provider.ts:424:43)
      at createClass (../packages/core/src/view/provider.ts:288:24)
      at createDirectiveInstance (../packages/core/src/view/provider.ts:142:7)
```

**Comment by Toub** [comment]
Corrigé via #976, à tester quand travis sera de retour

**Comment by Toub** [comment]
On peut fermer ce ticket, car y'a plus de travis.

On le ré-ouvrira si besoin si ça revient.
