### ISSUE TITLE
bug(stats): bug calcul des stats

### ISSUE THREAD

**Issue by Toub** [SocialGouv/domifa#985]
**Description du problème**

Le traitement de calcul des stats a un bug. Par ailleurs, le problème n'est pas remonté dans sentry.

Trace dans les logs en dev (avec base de tests):

```bash
(node:1258) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sum' of undefined
    at StatsGeneratorService.totalInteraction (/app/packages/backend/src/stats/services/stats-generator.service.ts:796:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at StatsGeneratorService.generateStats (/app/packages/backend/src/stats/services/stats-generator.service.ts:364:36)
```

**Comportement attendu**

- [x] corriger le bug
- [x] en cas d'erreur, logger un message d'erreur dans sentry
- [x] en cas d'erreur lors de la génération des stats d'une structure, poursuivre le traitement avec les autres structures

**Recette PO**

Rien à tester côté PO.

**Comment by Toub** [comment]
Pas de trace dans les logs de prod, donc ça doit être lié aux données.

**Comment by ledugong** [comment]
Non recettable PO
